### ISSUE TITLE
Some possible mistakes I found in `ioringnt.h`

### ISSUE THREAD

**Issue by CarterLi** [yardenshafir/IoRing_Demos#3]
* `IORING_QUEUE_HEAD`: should better be called `IORING_SUB_QUEUE_HEAD` to match `IORING_COMP_QUEUE_HEAD`
* `IORING_QUEUE_HEAD`::`QueueIndex`: should be `QueueHead` or `QueueHeadIndex`, which (actually `QueueHead & SubQueueSizeMask`) is the index of ring buffer head. Still don't know what `Aligment` (Alig`n`ment? typo?) means though
* `IORING_QUEUE_HEAD`::`QueueCount`: should be `QueueTail` or `QueueTailIndex`, which (actually `QueueTail & SubQueueSizeMask`) is the index of ring buffer tail
* `QueueCount - QueueIndex` has to be lower than total number of entries to be submitted ( i.e. submission queue size ). `QueueIndex + QueueCount` means nothing.
![image](https://user-images.githubusercontent.com/6134068/138510210-4437a78c-ab81-414d-a507-c2e5461d7a4a.png)
* `IORING_COMP_QUEUE_HEAD`::`QueueIndex` and `IORING_COMP_QUEUE_HEAD`::`QueueCount`: the same problem as `IORING_QUEUE_HEAD`. I am pretty sure. Please check twice.
* `NT_IORING_SQE`::`UserData`: should better be typed as `UINT_PTR`, to match `IORING_CQE`::`UserData` provided by `ioringapi.h`
* NtXxxFunctions: should better be tagged as `extern "c"` `NTAPI`

**Comment by yardenshafir** [comment]
A few answers, I'll try to answer as much as I can:
1. QueueIndex, QueueCount, other names - I agree that your naming makes more sense, I will update the header file with the names you suggested.  I will probably not update the writeup and code with the new names because... laziness. But I agree that these make more sense and are more in-sync with the Linux names.
The `Alignment` field was in fact a typo. This is just 8 bytes of padding because the SQEs themselves need to start on a 0x10 alignment. I'll rename it to `Padding`, it might make things clearer.
2. Your header is definitely nicer than mine - mine was thrown together to document the structures but I agree it's not the nicest or up to any decent coding style. I'll make it look a bit nicer, but probably not much.
3. Fixed the blog to have "QueueCount - QueueIndex" instead of "QueueIndex + QueueCount".
4. The `Key` field is passed into `IopReadFile`, which then goes into `IO_STATUS_BLOCK->Parameters.Read.Key`, it's not used for cancel operations.
5. The identifier for the canceled operation in `IORING_OP_CANCEL` operations goes into the `Buffer` field. The blog post didn't document everything, and I didn't feel the need to document all the things already mentioned in the header. Specifically `UserData` is used in all operations, not just `IORING_OP_CANCEL`. It's written directly into the CQE to help the caller identify the request. The system does nothing with it, it's entirely up to the caller to pass in `UserData` or pass in NULL. What do you mean by `people can't set the real user data they need`?
6. Good catch about the x86 sizes - I admit I didn't test this on x86 since Windows 10x86 is rare and not used very often. I'll update the header the same way you set up yours, to fix the sizes.

**Comment by CarterLi** [comment]
> What do you mean by `people can't set the real user data they need`?

Handle and op code are not unique.

Imaging I submitted 2 sqes with the same file handle and op code but different buffer and offset, for example:

1. IORING_OP_READ(handle=file1, buffer=1, bufferSize=32, offset=0)
2. IORING_OP_READ(handle=file1, buffer=2, bufferSize=32, offset=32)

Then I submit IORING_OP_CANCEL(handle=file1, opCode=IORING_OP_READ). Which sqe will be canceled in this case?

---

In linux, `user_data` is used as an identifer for finding the old sqe to be canceled.

https://github.com/axboe/liburing/blob/master/man/io_uring_enter.2#L535

In `ntioring_x.h` we have similar comments: `The UserData for the operation to cancel is used to identify the operation`. Hence the question

**Comment by CarterLi** [comment]
> The Key field is passed into IopReadFile, which then goes into IO_STATUS_BLOCK->Parameters.Read.Key, it's not used for cancel operations.

I still don't quite understand. What does it mean for users? What value should users set?

**Comment by CarterLi** [comment]
> I will probably not update the writeup and code with the new names because... laziness. But I agree that these make more sense and are more in-sync with the Linux names.

It's not only names, but also the whole explanation were not correct.

The article reads

> The queue header describes which entries should be processes using the QueueIndex and QueueCount fields. QueueIndex specifies the index of the first entry to be processes, and QueueCount specifies the amount of entries

`QueueHead & SubQueueSizeMask` specifies the index of the first entry to be processed. `QueueTail - QueueHead` specifies the amount of entries.

`QueueIndex specifies the index of the first entry to be processes` is acceptable but `QueueCount specifies the amount of entries` is not. It's obviously wrong and misleading.

**Comment by CarterLi** [comment]
Outdated
